export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_FAILURE = "FETCH_USERS_FAILURE";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";

/**
 *
 * LANGUAGE TYPES
 */

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";
export const UPDATE_LANGUAGE_LIST = "UPDATE_LANGUAGE_LIST";
export const RESET_LANGUAGE = "RESET_LANGUAGE";
